### ISSUE TITLE
`opta destroy -c flyte/opta/aws/env.yaml` doesn't destroy CloudWatch Log Group

### ISSUE THREAD

**Issue by anmyachev** [run-x/opta#641]
#### What happened:

First I ran the command: `opta apply -c flyte/opta/aws/env.yaml` that failed, see error below:

<details><summary>Error</summary>

```bash
module.k8sbase.helm_release.ingress-nginx: Still creating... [5m0s elapsed]
╵
╷
│ Error: release ingress-nginx failed, and has been uninstalled due to atomic being set: timed out waiting for the condition
│
│   with module.k8sbase.helm_release.ingress-nginx,
│   on .opta/modules/aws_k8s_base/tf_module/ingress_nginx.tf line 2, in resource "helm_release" "ingress-nginx":
│    2: resource "helm_release" "ingress-nginx" {
│
╵
ERROR: Command '['exec', 'terraform', 'apply', '-compact-warnings', 'tf.plan']' returned non-zero exit status 1.

```
</details>

Then I ran the command: `opta destroy -c flyte/opta/aws/env.yaml` which completed successfully.

After that I ran the command `opta apply -c flyte/opta/aws/env.yaml` again that failed, see error below:

<details><summary>Error</summary>

```bash
╷
│ Error: Creating CloudWatch Log Group failed: ResourceAlreadyExistsException: The specified log group already exists:  The CloudWatch Log Group '/aws/eks/opta-amyachev-env/cluster' already exists.
│
│   with module.k8scluster.aws_cloudwatch_log_group.cluster_logs,
│   on .opta/modules/aws_eks/tf_module/eks.tf line 74, in resource "aws_cloudwatch_log_group" "cluster_logs":
│   74: resource "aws_cloudwatch_log_group" "cluster_logs" {
│
╵
ERROR: Command '['exec', 'terraform', 'apply', '-compact-warnings', 'tf.plan']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "opta/cli.py", line 66, in <module>
  File "click/core.py", line 1128, in __call__
  File "click/core.py", line 1053, in main
  File "click/core.py", line 1659, in invoke
  File "click/core.py", line 1395, in invoke
  File "click/core.py", line 754, in invoke
  File "opta/commands/apply.py", line 105, in apply
  File "opta/commands/apply.py", line 323, in _apply
  File "opta/commands/apply.py", line 315, in _apply
  File "opta/commands/apply.py", line 310, in _apply
  File "opta/core/terraform.py", line 145, in apply
  File "opta/nice_subprocess.py", line 190, in nice_run
  File "opta/nice_subprocess.py", line 160, in nice_run
  File "opta/utils/runtee.py", line 157, in run
subprocess.CalledProcessError: Command '['exec', 'terraform', 'apply', '-compact-warnings', 'tf.plan']' returned non-zero exit status 1.
Unhandled error encountered -- a crash report zipfile has been createded for you. If you need more help please reach out (passing the crash report) to the contributors in our slack channel at: https://slack.opta.dev

```
</details>

#### What you expected to happen:

I expect that after the destroy command, there are no resources left

#### Environment:
- Opta version (use `opta version`): `x0.24.3`
- Cloud provider (or hardware configuration for local): `AWS`
- OS (e.g: `cat /etc/os-release`): `Ubuntu 20.04`
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by NitinAgg** [comment]
Thanks for the bug @anmyachev. We will aim to fix this bug by the release 0.26.0 (slated to be released in 2 weeks).
Meanwhile you can manually delete the cloudwatch log group in the aws UI before applying again.
