### ISSUE TITLE
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool

### ISSUE THREAD

**Issue by anmyachev** [run-x/opta#643]
#### What happened:

Run command: `opta apply -c flyte/opta/aws/env.yaml` failed, see error below.

<details><summary>Error</summary>

```bash
ERROR: HTTPSConnectionPool(host='04803a22277127da2dff766d486c4519.gr7.us-east-1.eks.amazonaws.com', port=443): Max retries exceeded with url: /api/v1/services (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa6a3f10580>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Traceback (most recent call last):
  File "urllib3/connection.py", line 174, in _new_conn
  File "urllib3/util/connection.py", line 72, in create_connection
  File "socket.py", line 918, in getaddrinfo
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 703, in urlopen
  File "urllib3/connectionpool.py", line 386, in _make_request
  File "urllib3/connectionpool.py", line 1040, in _validate_conn
  File "urllib3/connection.py", line 358, in connect
  File "urllib3/connection.py", line 186, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fa6a3f10580>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "opta/cli.py", line 66, in <module>
  File "click/core.py", line 1128, in __call__
  File "click/core.py", line 1053, in main
  File "click/core.py", line 1659, in invoke
  File "click/core.py", line 1395, in invoke
  File "click/core.py", line 754, in invoke
  File "opta/commands/apply.py", line 105, in apply
  File "opta/commands/apply.py", line 323, in _apply
  File "opta/commands/apply.py", line 210, in _apply
  File "opta/core/generator.py", line 84, in gen
  File "opta/layer.py", line 383, in gen_tf
  File "modules/aws_k8s_base/aws_k8s_base.py", line 45, in process
    self._process_nginx_extra_ports(self.module.data)
  File "modules/base.py", line 396, in _process_nginx_extra_ports
    service_port_mapping = reconcile_nginx_extra_ports(update_config_map=False)
  File "modules/base.py", line 651, in reconcile_nginx_extra_ports
    services = kubernetes.list_services()
  File "opta/core/kubernetes.py", line 566, in list_services
  File "kubernetes/client/api/core_v1_api.py", line 17764, in list_service_for_all_namespaces
  File "kubernetes/client/api/core_v1_api.py", line 17867, in list_service_for_all_namespaces_with_http_info
  File "kubernetes/client/api_client.py", line 348, in call_api
  File "kubernetes/client/api_client.py", line 180, in __call_api
  File "kubernetes/client/api_client.py", line 373, in request
  File "kubernetes/client/rest.py", line 239, in GET
  File "kubernetes/client/rest.py", line 212, in request
  File "urllib3/request.py", line 74, in request
  File "urllib3/request.py", line 96, in request_encode_url
  File "urllib3/poolmanager.py", line 375, in urlopen
  File "urllib3/connectionpool.py", line 813, in urlopen
  File "urllib3/connectionpool.py", line 813, in urlopen
  File "urllib3/connectionpool.py", line 813, in urlopen
  File "urllib3/connectionpool.py", line 785, in urlopen
  File "urllib3/util/retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='04803a22277127da2dff766d486c4519.gr7.us-east-1.eks.amazonaws.com', port=443): Max retries exceeded with url: /api/v1/services (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa6a3f10580>: Failed to establish a new connection: [Errno -2] Name or service not known'))

```

</details>

#### Anything else we need to know?:

[opta_crash_report (2).zip](https://github.com/run-x/opta/files/7959277/opta_crash_report.2.zip)

#### Environment:
- Opta version (use `opta version`): `v0.24.3`
- Cloud provider (or hardware configuration for local): `AWS`
- OS (e.g: `cat /etc/os-release`): `Ubuntu 20.04`
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by juandiegopalomino** [comment]
@anmyachev did this happen aftr destroying the environment and recreating it?

**Comment by anmyachev** [comment]
@juandiegopalomino yes, in addition, the same problem is observed by my colleague who works in a different region, but on the same account.

**Comment by juandiegopalomino** [comment]
OK, this is an issue due to caching of the kubeconfig. It has been fixed here https://github.com/run-x/opta/pull/622, and should be out on the next release. In the mean time do the following command to fix it: `rm -r ~/.opta/kubeconfigs`
