### ISSUE TITLE
k8s-manifest module broken

### ISSUE THREAD

**Issue by loomsen** [run-x/opta#864]
#### What happened:
When trying to use k8s-manifest, I get an error upon `generate-terraform`. It expects a kubeconfig file to be present at a specific path, instead of using the currently active kubeconfig context in terraform.

Error:
```
ERROR: [Errno 2] No such file or directory: '/home/nvarz/.opta/kubeconfigs/kubeconfig-integration-aws.yaml'
Traceback (most recent call last):
  File "opta/cli.py", line 77, in <module>
  File "click/core.py", line 1128, in __call__
  File "click/core.py", line 1053, in main
  File "click/core.py", line 1659, in invoke
  File "click/core.py", line 1395, in invoke
  File "click/core.py", line 754, in invoke
  File "click/decorators.py", line 26, in new_func
  File "opta/commands/generate_terraform.py", line 104, in generate_terraform
  File "opta/layer.py", line 421, in validate_required_path_dependencies
  File "opta/layer.py", line 415, in get_required_path_dependencies
  File "opta/layer.py", line 507, in processor_for
  File "modules/k8s_manifest/k8s_manifest.py", line 23, in __init__
    ) = self.get_k8s_config_context(layer)
  File "modules/k8s_manifest/k8s_manifest.py", line 38, in get_k8s_config_context
    with open(config_file_name, "r") as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/home/nvarz/.opta/kubeconfigs/kubeconfig-integration-aws.yaml'
Unhandled error encountered -- a crash report zipfile has been created for you. If you need more help please reach out (passing the crash report) to the contributors in our slack channel at: https://slack.opta.dev/
```

#### What you expected to happen:

Generate valid terraform from my k8s-manifest.

#### How to reproduce it (as minimally and precisely as possible):
opta.yaml:

```yaml
org_name: ddmit
name: integration
providers:
  aws:
    region: eu-central-1
    account_id: "123456789"
modules:
  - type: base
    vpc_log_retention: 3
  - type: k8s-cluster
    min_nodes: 1
    eks_log_retention: 3
    k8s_version: "1.22"
    node_launch_template:
      user_data: ""
  - type: k8s-base
    admin_arns:
      - arn:aws:iam::123456789:user/*
  - type: k8s-manifest
    file_path: custom/service-account-gitlab-runner.yaml
```

k8s-manifest:
```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-runner
  namespace: gitlab-runner
```

#### Environment:
```
{
  "opta_version": "0.30.2",
  "platform": "Linux",
  "os_name": "posix",
  "os_version": "#1 SMP PREEMPT Wed Apr 13 22:09:20 UTC 2022"
}
```

- Cloud provider (or hardware configuration for local):
AWS/Azure/GCP

**Comment by juandiegopalomino** [comment]
damn, that's dumb mistake-- will work on it!

**Comment by juandiegopalomino** [comment]
@loomsen fixed in https://github.com/run-x/opta/pull/873
